/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dani
 */
public class ConsultarExistencias extends javax.swing.JFrame {
static public ResultSet r;
static public ResultSet r2;
static public ResultSet r3;
static public ResultSet r4;
static public Connection connection;
    /**
     * Creates new form ConsultarExistencias
     */
    public ConsultarExistencias() throws SQLException {
        initComponents();
      String url ="jdbc:mysql://localhost:3306/tiendaanimales";
        String user="Dependiente";
        String contra="roto2";
        connection = DriverManager.getConnection(url,user,contra);
        
        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        txt1.setVisible(false);txt2.setVisible(false);txt3.setVisible(false);
        nombre1.setVisible(false);nombre2.setVisible(false);nombre3.setVisible(false);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        txt1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JTextField();
        txt3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consultar Existencias");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mas", "Menos" }));

        jLabel2.setText("Buscar productos que tengan...");

        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Existencias  o ");

        txt1.setText("Nombre");

        txt2.setText("Nombre");

        txt3.setText("Nombre");

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addComponent(nombre1)
                    .addComponent(nombre2)
                    .addComponent(nombre3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1)
                            .addComponent(txt2)
                            .addComponent(txt3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
        int numeros=Integer.parseInt(jTextField1.getText());
        String mm=(String) combo1.getSelectedItem();
        String query="";
        if(mm.equals("Mas")){
          query="SELECT cui.Nombre,obj.Nombre,comp.Nombre FROM Cuidados cui, Objetos obj, Complementos comp WHERE Existencias>="+numeros;  
        }
        else{
        query="SELECT cui.Nombre,obj.Nombre,comp.Nombre FROM Cuidados cui, Objetos obj, Complementos comp  WHERE Existencias<="+numeros; 
        }
    
        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r=s.executeQuery(query);
        if(r.next()){
            if(r.getString("cui.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("cui.Nombre"));
            }
            else if(r.getString("obj.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("comp.Nombre"));
            }else {txt1.setVisible(false); nombre1.setVisible(false);}
            if(r.getString("obj.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("comp.Nombre"));
            }else {txt2.setVisible(false); nombre2.setVisible(false);}
            if(r.getString("comp.Nombre")!=null){
                txt3.setVisible(true);
                nombre3.setVisible(true);
                nombre3.setText(r.getString("comp.Nombre"));
            }else{txt3.setVisible(false);nombre3.setVisible(false);}
            
        }
       
       } catch (SQLException ex) {
        Logger.getLogger(ConsultarExistencias.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
      char a=evt.getKeyChar();
      if(!Character.isDigit(a)){
          evt.consume();
      }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        if(r.next()){
            if(r.getString("cui.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("cui.Nombre"));
            }
            else if(r.getString("obj.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("comp.Nombre"));
            }else {txt1.setVisible(false); nombre1.setVisible(false);}
            if(r.getString("obj.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("comp.Nombre"));
            }else {txt2.setVisible(false); nombre2.setVisible(false);}
            if(r.getString("comp.Nombre")!=null){
                txt3.setVisible(true);
                nombre3.setVisible(true);
                nombre3.setText(r.getString("comp.Nombre"));
            }else{txt3.setVisible(false);nombre3.setVisible(false);}
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(ConsultarExistencias.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
        if(r.previous()){
            if(r.getString("cui.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("cui.Nombre"));
            }
            else if(r.getString("obj.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt1.setVisible(true);
                nombre1.setVisible(true);
                nombre1.setText(r.getString("comp.Nombre"));
            }else {txt1.setVisible(false); nombre1.setVisible(false);}
            if(r.getString("obj.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("obj.Nombre"));
            }
            else if(r.getString("comp.Nombre")!=null){
                txt2.setVisible(true);
                nombre2.setVisible(true);
                nombre2.setText(r.getString("comp.Nombre"));
            }else {txt2.setVisible(false); nombre2.setVisible(false);}
            if(r.getString("comp.Nombre")!=null){
                txt3.setVisible(true);
                nombre3.setVisible(true);
                nombre3.setText(r.getString("comp.Nombre"));
            }else{txt3.setVisible(false);nombre3.setVisible(false);}
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(ConsultarExistencias.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JTextField nombre3;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    // End of variables declaration//GEN-END:variables
}
