/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import static proyecto.ProductosFactura.connection;
import static proyecto.ProductosFactura.r;

/**
 *
 * @author AlumMati
 */
public class Facturas extends javax.swing.JFrame {
    static public ResultSet r2;
    static public ResultSet r3;
static public Connection con;
  
    public Facturas() throws SQLException {
        initComponents();
         aceptarbutton.setVisible(false);
        aceptarbutton.setVisible(false);
        cancelbutton.setEnabled(false);
        cancelbutton.setVisible(false);
         Login log = new Login();
        String url ="jdbc:mysql://localhost:3306/tiendaanimales";
        String user="Dependiente";
        String contra="roto2";
        connection = DriverManager.getConnection(url,user,contra);        
        regenerardatos();
     
       
    }
     public void regenerardatos() throws SQLException{
        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query="SELECT * FROM FACTURAS";
        r3=s.executeQuery(query);
        r3.first();
        Identificador.setText(r3.getString("IdFactura"));
        PrecioTotal.setText(r3.getString("Precio"));
        Fechancala.setText(r3.getString("Fecha"));
        }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editarbutton = new javax.swing.JButton();
        Identificador = new javax.swing.JTextField();
        nuevobutton = new javax.swing.JButton();
        aceptarbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrecioTotal = new javax.swing.JTextField();
        Fechancala = new javax.swing.JTextField();
        anteriorbutton = new javax.swing.JButton();
        siguientebutton = new javax.swing.JButton();
        primerobutton = new javax.swing.JButton();
        ultimobutton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Facturas");

        editarbutton.setText("Editar");
        editarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbuttonActionPerformed(evt);
            }
        });

        Identificador.setEnabled(false);
        Identificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorActionPerformed(evt);
            }
        });

        nuevobutton.setText("Nuevo");
        nuevobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobuttonActionPerformed(evt);
            }
        });

        aceptarbutton.setText("Aceptar");
        aceptarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Cancelar");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/foto2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Identificador");

        jLabel4.setText("Precio total");

        jLabel5.setText("Fecha");

        PrecioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTotalActionPerformed(evt);
            }
        });

        Fechancala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechancalaActionPerformed(evt);
            }
        });

        anteriorbutton.setText("Anterior");
        anteriorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorbuttonActionPerformed(evt);
            }
        });

        siguientebutton.setText("Siguiente");
        siguientebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientebuttonActionPerformed(evt);
            }
        });

        primerobutton.setText("Primero");
        primerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerobuttonActionPerformed(evt);
            }
        });

        ultimobutton.setText("Ultimo");
        ultimobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(PrecioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fechancala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aceptarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ultimobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anteriorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(siguientebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(primerobutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(anteriorbutton)
                    .addComponent(siguientebutton)
                    .addComponent(aceptarbutton))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ultimobutton)
                        .addComponent(primerobutton)
                        .addComponent(cancelbutton)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Fechancala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarbutton)
                    .addComponent(nuevobutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorActionPerformed

    private void PrecioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTotalActionPerformed

    private void FechancalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechancalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechancalaActionPerformed

    private void anteriorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorbuttonActionPerformed
        try {
            if(r3.previous()){
                 Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
            }} catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anteriorbuttonActionPerformed

    private void siguientebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientebuttonActionPerformed
        try {
            if(r3.next()){
                 Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
            }} catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siguientebuttonActionPerformed

    private void primerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerobuttonActionPerformed
        try {
            r3.first();
              Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_primerobuttonActionPerformed

    private void ultimobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimobuttonActionPerformed
             try {
            r3.last();
              Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ultimobuttonActionPerformed

    private void editarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbuttonActionPerformed
        String uno=PrecioTotal.getText();
        String dos=Fechancala.getText();
        String asd=Identificador.getText();
        String query2="UPDATE facturas SET Fecha='"+dos+"',Precio="+uno+" WHERE IdFactura="+asd;
         Statement s2;
        try {
            s2 = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);       
        int r=s2.executeUpdate(query2);         
           Facturas f = new Facturas ();    
           f = new Facturas();
           f.setVisible(true);
            this.setVisible(false);
            f.setLocationRelativeTo(null);
       
         } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarbuttonActionPerformed

    private void nuevobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobuttonActionPerformed
       Identificador.setEnabled(true);
       Identificador.setText("");
       PrecioTotal.setText("");
       Fechancala.setText("");       
        aceptarbutton.setVisible(true); aceptarbutton.setVisible(true);
        cancelbutton.setEnabled(true);  cancelbutton.setVisible(true);
        siguientebutton.setVisible(false); siguientebutton.setEnabled(false);
        anteriorbutton.setVisible(false); anteriorbutton.setEnabled(false);
        primerobutton.setVisible(false); primerobutton.setEnabled(false);
        ultimobutton.setVisible(false); ultimobutton.setEnabled(false);
        editarbutton.setVisible(false); editarbutton.setEnabled(false);
        nuevobutton.setVisible(false); nuevobutton.setEnabled(false);
    }//GEN-LAST:event_nuevobuttonActionPerformed

    private void aceptarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarbuttonActionPerformed
        String uno=PrecioTotal.getText();
        String dos=Fechancala.getText();
        String asd=Identificador.getText();
        String query3="INSERT INTO facturas VALUES("+asd+",'"+dos+"',"+uno+")";
        Statement s3;
        try { 
            s3= (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            int r=s3.executeUpdate(query3);        
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Identificador.setEnabled(false);
        aceptarbutton.setVisible(false); aceptarbutton.setVisible(false);
        cancelbutton.setEnabled(false);  cancelbutton.setVisible(false);
        siguientebutton.setVisible(true); siguientebutton.setEnabled(true);
        anteriorbutton.setVisible(true); anteriorbutton.setEnabled(true);
        primerobutton.setVisible(true); primerobutton.setEnabled(true);
        ultimobutton.setVisible(true); ultimobutton.setEnabled(true);
        editarbutton.setVisible(true); editarbutton.setEnabled(true);
        nuevobutton.setVisible(true); nuevobutton.setEnabled(true);
         try {
           Facturas f = new Facturas ();    
           f = new Facturas();
           f.setVisible(true);
            this.setVisible(false);
            f.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        Identificador.setEnabled(false);
        aceptarbutton.setVisible(false); aceptarbutton.setVisible(false);
        cancelbutton.setEnabled(false);  cancelbutton.setVisible(false);
        siguientebutton.setVisible(true); siguientebutton.setEnabled(true);
        anteriorbutton.setVisible(true); anteriorbutton.setEnabled(true);
        primerobutton.setVisible(true); primerobutton.setEnabled(true);
        ultimobutton.setVisible(true); ultimobutton.setEnabled(true);
        editarbutton.setVisible(true); editarbutton.setEnabled(true);
        nuevobutton.setVisible(true); nuevobutton.setEnabled(true);
        try {
            regenerardatos();
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login log = new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.setVisible(false);
        try {
            log.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menyo=new Menu();
        this.setVisible(false);
        menyo.setVisible(true);
        menyo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fechancala;
    private javax.swing.JTextField Identificador;
    private javax.swing.JTextField PrecioTotal;
    private javax.swing.JButton aceptarbutton;
    private javax.swing.JButton anteriorbutton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton editarbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevobutton;
    private javax.swing.JButton primerobutton;
    private javax.swing.JButton siguientebutton;
    private javax.swing.JButton ultimobutton;
    // End of variables declaration//GEN-END:variables
}
